services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sabine-website
    container_name: sabine-website
    restart: always
    ports:
      - '7000:3000'
    network_mode: host